name: cvar-index
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - jupyter>=1.0.0
  - notebook>=6.5.0
  - ipykernel>=6.20.0
  - pip>=23.0
  - pip:
    - cvxpy>=1.4.0
    - yfinance>=0.2.0
    - scikit-learn>=1.0.0
    - pytest>=7.2.0
    - pytest-cov>=4.0.0
    - mypy>=1.0.0
    - black>=23.0.0
    - flake8>=6.0.0
    - isort>=5.12.0
    - tqdm>=4.64.0
    - openpyxl>=3.1.0
    - xlsxwriter>=3.0.0
    - pandas-market-calendars>=4.3.0
    - shap>=0.42.0 